### ISSUE TITLE
jspServletHolder() does not seem to have a purpose

### ISSUE THREAD

**Issue by fatso83** [jetty-project/embedded-jetty-jsp#11]
If I comment out [the call that adds `jspServletHolder()` as a servlet](https://github.com/jetty-project/embedded-jetty-jsp/blob/master/src/main/java/org/eclipse/jetty/demo/Main.java#L165), all code still seems to work just fine. It is as if there is some default servlet that overrides it. A simple JSP actually runs just fine even after commenting out _all_ the servlets ... So what use is the `jspServletHolder` function?

**Comment by gregw** [comment]
Because this example uses a WebAppContext as the base, it will be looking for the `defaultweb.xml` which also adds the JSP servlet.

Thus you are right, the explicit adding of the JSP servlet is not necessary in this example.

We should look at either using a simple ServletContextHandler instead (to avoid the `defaultweb.xml`) or perhaps use an explicit default descriptor with less in in.

**Comment by janbartel** [comment]
I think a long time ago this example used to use a version of jetty with a different jsp setup that worked with a ServletContextHandler. Then it was changed to needing a WebAppContext because of all the machinery (annotations etc) that the newer jsp engine needed.

I'll revisit this and see if there is a way to make this work again with a ServletContextHandler again.

**Comment by janbartel** [comment]
Changed back to a ServletContextHandler - a little clunky but it works.

**Comment by fatso83** [comment]
Thanks, that made sense.
